# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: ab992d67876f5146e7154fe1644353bdb36d07373f788e8269d3fe32bb3c6a3b6ad7556d7aab107f69e803e7ba798bbabd93d29a1780f48e130fc25cdb52b902

test:
  secret_key_base: 573594111c519de3e7ff5daf5e21873ac1597087cb8f078e5df282aec6a0a40a4e37611d37cba8f5ed2a1d05debd647b6c6480ceed82aa0eec991faacebfcd10

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
